<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime-3.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\MercuryEntitySelector\Priority instead.
     * @deprecated
     */
    class MercuryEntitySelector_Priority {}
}
class_exists(MercuryEntitySelector\Priority::class);
@trigger_error('Transit_realtime\MercuryEntitySelector_Priority is deprecated and will be removed in the next major release. Use Transit_realtime\MercuryEntitySelector\Priority instead', E_USER_DEPRECATED);

