<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime-mta.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\MercuryEntitySelector\NyctBusPriority instead.
     * @deprecated
     */
    class MercuryEntitySelector_NyctBusPriority {}
}
class_exists(MercuryEntitySelector\NyctBusPriority::class);
@trigger_error('Transit_realtime\MercuryEntitySelector_NyctBusPriority is deprecated and will be removed in the next major release. Use Transit_realtime\MercuryEntitySelector\NyctBusPriority instead', E_USER_DEPRECATED);

