<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime-mta.proto

namespace Transit_realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mercury extensions for the Feed Header
 *
 * Generated from protobuf message <code>transit_realtime.MercuryFeedHeader</code>
 */
class MercuryFeedHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * Version of the Mercury extensions
     * The current version is 1.0
     *
     * Generated from protobuf field <code>string mercury_version = 1;</code>
     */
    protected $mercury_version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mercury_version
     *           Version of the Mercury extensions
     *           The current version is 1.0
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GtfsRealtimeMta::initOnce();
        parent::__construct($data);
    }

    /**
     * Version of the Mercury extensions
     * The current version is 1.0
     *
     * Generated from protobuf field <code>string mercury_version = 1;</code>
     * @return string
     */
    public function getMercuryVersion()
    {
        return $this->mercury_version;
    }

    /**
     * Version of the Mercury extensions
     * The current version is 1.0
     *
     * Generated from protobuf field <code>string mercury_version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMercuryVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->mercury_version = $var;

        return $this;
    }

}

