<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime-3.proto

namespace Transit_realtime\MercuryEntitySelector;

use UnexpectedValueException;

/**
 * Protobuf type <code>transit_realtime.MercuryEntitySelector.NyctBusPriority</code>
 */
class NyctBusPriority
{
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_NOT_USED = 0;</code>
     */
    const NYCT_BUS_PRIORITY_NOT_USED = 0;
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_NO_SCHEDULED_SERVICE = 1;</code>
     */
    const NYCT_BUS_PRIORITY_NO_SCHEDULED_SERVICE = 1;
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_SUNDAY_SCHEDULE = 2;</code>
     */
    const NYCT_BUS_PRIORITY_SUNDAY_SCHEDULE = 2;
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_SATURDAY_SCHEDULE = 3;</code>
     */
    const NYCT_BUS_PRIORITY_SATURDAY_SCHEDULE = 3;
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_HOLIDAY_SERVICE = 4;</code>
     */
    const NYCT_BUS_PRIORITY_HOLIDAY_SERVICE = 4;
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_PLANNED_DETOUR = 5;</code>
     */
    const NYCT_BUS_PRIORITY_PLANNED_DETOUR = 5;
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_EXTRA_SERVICE = 6;</code>
     */
    const NYCT_BUS_PRIORITY_EXTRA_SERVICE = 6;
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_PLANNED_WORK = 7;</code>
     */
    const NYCT_BUS_PRIORITY_PLANNED_WORK = 7;
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_SPECIAL_EVENT = 11;</code>
     */
    const NYCT_BUS_PRIORITY_SPECIAL_EVENT = 11;
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_DELAYS = 13;</code>
     */
    const NYCT_BUS_PRIORITY_DELAYS = 13;
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_DETOURS = 16;</code>
     */
    const NYCT_BUS_PRIORITY_DETOURS = 16;
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_SERVICE_CHANGE = 18;</code>
     */
    const NYCT_BUS_PRIORITY_SERVICE_CHANGE = 18;
    /**
     * Generated from protobuf enum <code>NYCT_BUS_PRIORITY_SUSPENDED = 22;</code>
     */
    const NYCT_BUS_PRIORITY_SUSPENDED = 22;

    private static $valueToName = [
        self::NYCT_BUS_PRIORITY_NOT_USED => 'NYCT_BUS_PRIORITY_NOT_USED',
        self::NYCT_BUS_PRIORITY_NO_SCHEDULED_SERVICE => 'NYCT_BUS_PRIORITY_NO_SCHEDULED_SERVICE',
        self::NYCT_BUS_PRIORITY_SUNDAY_SCHEDULE => 'NYCT_BUS_PRIORITY_SUNDAY_SCHEDULE',
        self::NYCT_BUS_PRIORITY_SATURDAY_SCHEDULE => 'NYCT_BUS_PRIORITY_SATURDAY_SCHEDULE',
        self::NYCT_BUS_PRIORITY_HOLIDAY_SERVICE => 'NYCT_BUS_PRIORITY_HOLIDAY_SERVICE',
        self::NYCT_BUS_PRIORITY_PLANNED_DETOUR => 'NYCT_BUS_PRIORITY_PLANNED_DETOUR',
        self::NYCT_BUS_PRIORITY_EXTRA_SERVICE => 'NYCT_BUS_PRIORITY_EXTRA_SERVICE',
        self::NYCT_BUS_PRIORITY_PLANNED_WORK => 'NYCT_BUS_PRIORITY_PLANNED_WORK',
        self::NYCT_BUS_PRIORITY_SPECIAL_EVENT => 'NYCT_BUS_PRIORITY_SPECIAL_EVENT',
        self::NYCT_BUS_PRIORITY_DELAYS => 'NYCT_BUS_PRIORITY_DELAYS',
        self::NYCT_BUS_PRIORITY_DETOURS => 'NYCT_BUS_PRIORITY_DETOURS',
        self::NYCT_BUS_PRIORITY_SERVICE_CHANGE => 'NYCT_BUS_PRIORITY_SERVICE_CHANGE',
        self::NYCT_BUS_PRIORITY_SUSPENDED => 'NYCT_BUS_PRIORITY_SUSPENDED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(NyctBusPriority::class, \Transit_realtime\MercuryEntitySelector_NyctBusPriority::class);

