<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime-mta.proto

namespace Transit_realtime\MercuryEntitySelector;

use UnexpectedValueException;

/**
 * Protobuf type <code>transit_realtime.MercuryEntitySelector.Priority</code>
 */
class Priority
{
    /**
     * Generated from protobuf enum <code>PRIORITY_NOT_USED = 0;</code>
     */
    const PRIORITY_NOT_USED = 0;
    /**
     * Generated from protobuf enum <code>PRIORITY_NO_SCHEDULED_SERVICE = 1;</code>
     */
    const PRIORITY_NO_SCHEDULED_SERVICE = 1;
    /**
     * Generated from protobuf enum <code>PRIORITY_SUNDAY_SCHEDULE = 2;</code>
     */
    const PRIORITY_SUNDAY_SCHEDULE = 2;
    /**
     * Generated from protobuf enum <code>PRIORITY_SATURDAY_SCHEDULE = 3;</code>
     */
    const PRIORITY_SATURDAY_SCHEDULE = 3;
    /**
     * Generated from protobuf enum <code>PRIORITY_HOLIDAY_SERVICE = 4;</code>
     */
    const PRIORITY_HOLIDAY_SERVICE = 4;
    /**
     * Generated from protobuf enum <code>PRIORITY_EXTRA_SERVICE = 5;</code>
     */
    const PRIORITY_EXTRA_SERVICE = 5;
    /**
     * Generated from protobuf enum <code>PRIORITY_PLANNED_WORK = 6;</code>
     */
    const PRIORITY_PLANNED_WORK = 6;
    /**
     * Generated from protobuf enum <code>PRIORITY_ON_OR_CLOSE = 7;</code>
     */
    const PRIORITY_ON_OR_CLOSE = 7;
    /**
     * Generated from protobuf enum <code>PRIORITY_SLOW_SPEEDS = 8;</code>
     */
    const PRIORITY_SLOW_SPEEDS = 8;
    /**
     * Generated from protobuf enum <code>PRIORITY_SOME_DELAYS = 9;</code>
     */
    const PRIORITY_SOME_DELAYS = 9;
    /**
     * Generated from protobuf enum <code>PRIORITY_SPECIAL_EVENT = 10;</code>
     */
    const PRIORITY_SPECIAL_EVENT = 10;
    /**
     * Generated from protobuf enum <code>PRIORITY_STATIONS_SKIPPED = 11;</code>
     */
    const PRIORITY_STATIONS_SKIPPED = 11;
    /**
     * Generated from protobuf enum <code>PRIORITY_DELAYS = 12;</code>
     */
    const PRIORITY_DELAYS = 12;
    /**
     * Generated from protobuf enum <code>PRIORITY_EXPRESS_TO_LOCAL = 13;</code>
     */
    const PRIORITY_EXPRESS_TO_LOCAL = 13;
    /**
     * Generated from protobuf enum <code>PRIORITY_SOME_REROUTES = 14;</code>
     */
    const PRIORITY_SOME_REROUTES = 14;
    /**
     * Generated from protobuf enum <code>PRIORITY_LOCAL_TO_EXPRESS = 15;</code>
     */
    const PRIORITY_LOCAL_TO_EXPRESS = 15;
    /**
     * Generated from protobuf enum <code>PRIORITY_SERVICE_CHANGE = 16;</code>
     */
    const PRIORITY_SERVICE_CHANGE = 16;
    /**
     * Generated from protobuf enum <code>PRIORITY_TRAINS_REROUTED = 17;</code>
     */
    const PRIORITY_TRAINS_REROUTED = 17;
    /**
     * Generated from protobuf enum <code>PRIORITY_PART_SUSPENDED = 18;</code>
     */
    const PRIORITY_PART_SUSPENDED = 18;
    /**
     * Generated from protobuf enum <code>PRIORITY_MULTIPLE_IMPACTS = 19;</code>
     */
    const PRIORITY_MULTIPLE_IMPACTS = 19;
    /**
     * Generated from protobuf enum <code>PRIORITY_SUSPENDED = 20;</code>
     */
    const PRIORITY_SUSPENDED = 20;
    /**
     * Generated from protobuf enum <code>PRIORITY_BUSING = 21;</code>
     */
    const PRIORITY_BUSING = 21;

    private static $valueToName = [
        self::PRIORITY_NOT_USED => 'PRIORITY_NOT_USED',
        self::PRIORITY_NO_SCHEDULED_SERVICE => 'PRIORITY_NO_SCHEDULED_SERVICE',
        self::PRIORITY_SUNDAY_SCHEDULE => 'PRIORITY_SUNDAY_SCHEDULE',
        self::PRIORITY_SATURDAY_SCHEDULE => 'PRIORITY_SATURDAY_SCHEDULE',
        self::PRIORITY_HOLIDAY_SERVICE => 'PRIORITY_HOLIDAY_SERVICE',
        self::PRIORITY_EXTRA_SERVICE => 'PRIORITY_EXTRA_SERVICE',
        self::PRIORITY_PLANNED_WORK => 'PRIORITY_PLANNED_WORK',
        self::PRIORITY_ON_OR_CLOSE => 'PRIORITY_ON_OR_CLOSE',
        self::PRIORITY_SLOW_SPEEDS => 'PRIORITY_SLOW_SPEEDS',
        self::PRIORITY_SOME_DELAYS => 'PRIORITY_SOME_DELAYS',
        self::PRIORITY_SPECIAL_EVENT => 'PRIORITY_SPECIAL_EVENT',
        self::PRIORITY_STATIONS_SKIPPED => 'PRIORITY_STATIONS_SKIPPED',
        self::PRIORITY_DELAYS => 'PRIORITY_DELAYS',
        self::PRIORITY_EXPRESS_TO_LOCAL => 'PRIORITY_EXPRESS_TO_LOCAL',
        self::PRIORITY_SOME_REROUTES => 'PRIORITY_SOME_REROUTES',
        self::PRIORITY_LOCAL_TO_EXPRESS => 'PRIORITY_LOCAL_TO_EXPRESS',
        self::PRIORITY_SERVICE_CHANGE => 'PRIORITY_SERVICE_CHANGE',
        self::PRIORITY_TRAINS_REROUTED => 'PRIORITY_TRAINS_REROUTED',
        self::PRIORITY_PART_SUSPENDED => 'PRIORITY_PART_SUSPENDED',
        self::PRIORITY_MULTIPLE_IMPACTS => 'PRIORITY_MULTIPLE_IMPACTS',
        self::PRIORITY_SUSPENDED => 'PRIORITY_SUSPENDED',
        self::PRIORITY_BUSING => 'PRIORITY_BUSING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Priority::class, \Transit_realtime\MercuryEntitySelector_Priority::class);

